<?php

namespace AppBundle\Repository;

/**
 * productoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productoRepository extends \Doctrine\ORM\EntityRepository
{
}
